import { useMemo } from 'react'
import { useGameState } from '../lib/gameSession'
import { shuffledCycleIndex, shuffle } from '../lib/questionFlow'
import { addStars, getRecommendedDifficulty, type Difficulty } from '../lib/progress'
import { playCorrect, playIncorrect } from '../lib/sfx'
import { recordAnswer } from '../lib/review'

const qs=[['Ceará','Nordeste'],['Amazonas','Norte'],['São Paulo','Sudeste'],['Paraná','Sul'],['Goiás','Centro-Oeste'],['Bahia','Nordeste'],['Pará','Norte'],['Minas Gerais','Sudeste'],['Acre','Norte'],['Rondônia','Norte'],['Maranhão','Nordeste'],['Pernambuco','Nordeste'],['Mato Grosso','Centro-Oeste'],['Mato Grosso do Sul','Centro-Oeste'],['Espírito Santo','Sudeste'],['Rio de Janeiro','Sudeste'],['Santa Catarina','Sul'],['Rio Grande do Sul','Sul'],['Tocantins','Norte'],['Alagoas','Nordeste'],['Amapá','Norte'],['Roraima','Norte'],['Sergipe','Nordeste'],['Paraíba','Nordeste'],['Piauí','Nordeste'],['Rio Grande do Norte','Nordeste'],['Distrito Federal','Centro-Oeste']]
const REGIONS=['Norte','Nordeste','Centro-Oeste','Sudeste','Sul']
export default function BrazilRegionsGame(){const [level,setLevel]=useGameState<Difficulty>(()=>getRecommendedDifficulty('regions'));const [i,setI]=useGameState(0);const [score,setScore]=useGameState(0);const [msg,setMsg]=useGameState('');const [resolved,setResolved]=useGameState(false);const deck=level==='easy'?qs.slice(0,6):level==='medium'?qs.slice(5,13):qs.slice(12);const q=deck[shuffledCycleIndex(deck.length,i,`regions:${level}`)];const opts=useMemo(()=>shuffle(REGIONS),[i]);function choose(r:string){if(resolved)return;const ok=r===q[1];recordAnswer('regions',`Em qual região fica ${q[0]}?`,r,q[1],ok,'Os estados e o Distrito Federal estão distribuídos pelas cinco regiões do Brasil.');if(ok){setResolved(true);setScore(s=>s+1);addStars('regions',1);playCorrect();setMsg('Muito bem! 🇧🇷');setTimeout(()=>{setI(x=>x+1);setMsg('');setResolved(false)},600)}else{playIncorrect();setMsg('Tente lembrar em qual parte do mapa essa unidade federativa fica.')}}return <div className="container"><div className="game"><h2>Regiões do Brasil 🇧🇷🗺️</h2><p>Em qual região brasileira fica a unidade federativa abaixo?</p><div className="row difficulty-picker"><label htmlFor="regions-level">Nível:</label><select id="regions-level" value={level} disabled={resolved} onChange={e=>{setLevel(e.target.value as Difficulty);setI(0);setScore(0);setResolved(false);setMsg('')}}><option value="easy">Começando · estados conhecidos</option><option value="medium">Praticando · explore o mapa</option><option value="hard">Desafio · todos os estados e o DF</option></select></div><div className="state-card">📍 {q[0]}</div><div className="choice-grid">{opts.map(o=><button key={o} disabled={resolved} onClick={()=>choose(o)}>{o}</button>)}</div><p className="game-message" aria-live="polite">Acertos: {score} · {msg}</p></div></div>}
