import { useMemo } from 'react'
import { useGameState } from '../lib/gameSession'
import { addStars, getRecommendedDifficulty, type Difficulty } from '../lib/progress'
import { playCorrect, playIncorrect } from '../lib/sfx'
import { recordAnswer } from '../lib/review'

const times=[['06:00','seis horas'],['07:00','sete horas'],['08:30','oito e meia'],['09:15','nove e quinze'],['10:00','dez horas'],['11:45','onze e quarenta e cinco'],['12:30','doze e meia'],['13:00','uma da tarde'],['14:15','duas e quinze da tarde'],['15:00','três da tarde'],['16:30','quatro e meia da tarde'],['17:45','cinco e quarenta e cinco da tarde'],['18:30','seis e meia da tarde'],['19:00','sete da noite'],['20:15','oito e quinze da noite'],['21:00','nove da noite']]
export default function ClockGame(){const [level,setLevel]=useGameState<Difficulty>(()=>getRecommendedDifficulty('clock'));const [i,setI]=useGameState(0);const [msg,setMsg]=useGameState('');const [score,setScore]=useGameState(0);const [resolved,setResolved]=useGameState(false);const deck=times.filter(([time])=>level==='easy'?time.endsWith(':00'):level==='medium'?time.endsWith(':00')||time.endsWith(':30'):true);const item=deck[i%deck.length];const opts=useMemo(()=>[item[1],...deck.filter(x=>x[1]!==item[1]).sort(()=>Math.random()-.5).slice(0,3).map(x=>x[1])].sort(()=>Math.random()-.5),[i,level]);
 function pick(o:string){if(resolved)return;const ok=o===item[1];recordAnswer('clock',`Que horas são ${item[0]}?`,o,item[1],ok,'O relógio digital mostra a hora antes dos dois pontos e os minutos depois deles.');if(ok){setResolved(true);addStars('clock',1);playCorrect();setScore(s=>s+1);setMsg('Isso mesmo! ⏰');setTimeout(()=>{setI(x=>x+1);setMsg('');setResolved(false)},650)}else{playIncorrect();setMsg('Observe os números do relógio e tente de novo.')}}
 return <div className="container"><div className="game"><h2>Que Horas São? ⏰</h2><p>Leia o relógio digital e escolha como falamos esse horário.</p><div className="row difficulty-picker"><label htmlFor="clock-level">Nível:</label><select id="clock-level" value={level} onChange={e=>{setLevel(e.target.value as Difficulty);setI(0);setResolved(false);setMsg('')}}><option value="easy">Começando · horas cheias</option><option value="medium">Praticando · horas e meia</option><option value="hard">Desafio · horários variados</option></select></div><div className="digital-clock">{item[0]}</div><div className="choice-grid">{opts.map(o=><button key={o} disabled={resolved} onClick={()=>pick(o)}>{o}</button>)}</div><p className="game-message" aria-live="polite">Acertos: {score} · {msg}</p></div></div>}
