import { useMemo } from 'react'
import { useGameState } from '../lib/gameSession'
import { addStars, getRecommendedDifficulty, type Difficulty } from '../lib/progress'
import { playCorrect, playIncorrect } from '../lib/sfx'
import { recordAnswer } from '../lib/review'

const animals=[['🐟','Peixe','Água'],['🐒','Macaco','Floresta'],['🐪','Camelo','Deserto'],['🐧','Pinguim','Região gelada'],['🦁','Leão','Savana'],['🐸','Sapo','Áreas úmidas'],['🐬','Golfinho','Água'],['🦥','Bicho-preguiça','Floresta'],['🦎','Lagarto','Deserto'],['🐻‍❄️','Urso-polar','Região gelada'],['🦓','Zebra','Savana'],['🦆','Pato','Áreas úmidas'],['🦊','Raposa','Floresta'],['🐊','Jacaré','Áreas úmidas'],['🦦','Lontra','Água'],['🐨','Coala','Floresta'],['🐫','Dromedário','Deserto'],['🦩','Flamingo','Áreas úmidas'],['🐘','Elefante','Savana'],['🦌','Cervo','Floresta']]
const habitats=['Água','Floresta','Deserto','Região gelada','Savana','Áreas úmidas']
export default function HabitatGame(){const [level,setLevel]=useGameState<Difficulty>(()=>getRecommendedDifficulty('habitat'));const [i,setI]=useGameState(0);const [msg,setMsg]=useGameState('');const [resolved,setResolved]=useGameState(false);const a=animals[i%animals.length];const optionCount=level==='easy'?2:level==='medium'?4:habitats.length;const opts=useMemo(()=>[a[2],...habitats.filter(h=>h!==a[2]).sort(()=>Math.random()-.5).slice(0,optionCount-1)].sort(()=>Math.random()-.5),[i,level]);function choose(o:string){if(resolved)return;const ok=o===a[2];recordAnswer('habitat',`Onde vive o(a) ${a[1]}?`,o,a[2],ok,'O habitat oferece ao animal condições para encontrar alimento, abrigo e sobreviver.');if(ok){setResolved(true);addStars('habitat',1);playCorrect();setMsg('Habitat correto! 🌿');setTimeout(()=>{setI(x=>x+1);setMsg('');setResolved(false)},650)}else{playIncorrect();setMsg('Pense no clima e no lugar onde esse animal vive.') }}return <div className="container"><div className="game"><h2>Onde Eu Vivo? 🐾🌍</h2><p>Relacione cada animal ao seu habitat.</p><div className="row difficulty-picker"><label htmlFor="habitat-level">Nível:</label><select id="habitat-level" value={level} onChange={e=>{setLevel(e.target.value as Difficulty);setI(0);setMsg('');setResolved(false)}}><option value="easy">Começando · 2 opções</option><option value="medium">Praticando · 4 opções</option><option value="hard">Desafio · 6 opções</option></select></div><div className="animal-card"><span>{a[0]}</span><strong>{a[1]}</strong></div><div className="choice-grid">{opts.map(o=><button key={o} disabled={resolved} onClick={()=>choose(o)}>{o}</button>)}</div><p className="game-message" aria-live="polite">{msg}</p></div></div>}
